### ISSUE TITLE
installation in moodle 3... 

### ISSUE THREAD

**Issue by sberger** [TUM-MZ/moodle-block_material-download#8] opened 2016-02-02 13:52 UTC
manual installation at webfrontend dosnt work:
see: [https://moodle.org/mod/forum/discuss.php?d=326464#p1315424]
![bildschirmfoto 2016-02-02 um 14 14 56](https://cloud.githubusercontent.com/assets/3737740/12751288/9c029df6-c9bc-11e5-8b49-a82a05078424.png)

**Comment by sanmen1593** [comment] 2016-07-22 19:58
I have the same problem with my Moodle 3.1. Any hints about how to solve this?

**Comment by rezaugg** [comment] 2016-07-29 13:47
Soeben getestet in 3.1.1 - funktioniert

Installieren:
Herunterladen --> entpacken --> Ordner umbenennen in 'material_download' --> in moodle/blocks verschieben --> installieren via Website-Administration/Mitteilungen

Viel Erfolg und einmal mehr ein herzliches Dankeschön nach München für dieses tolle PlugIn!
Regina Zaugg

**Comment by alendit** [comment] 2016-08-19 09:40
Hi, 

I cannot reproduce the issue. My steps:
1. Download the lastest zipped plugin from https://github.com/TUM-MZ/moodle-block_material-download/archive/master.zip
2. Upload the `.zip` to the plugin installation form. 
3. Make sure your apache/nginx daemon has writin rights for the moodle source folder (which is absolutely not recommended for a productive deployment)
4. Click `next` couple of times.

I'm closing the issue for now. Please try with the newest version and if you still have this problem, comment here.

**Closed as completed by alendit** 2016-08-19 09:40 UTC

**Comment by sanmen1593** [comment] 2016-08-23 20:03
Hi

I solved this error by changing folder name after unzip to: block_material-download.

Thanks.
